#!/usr/bin/env bash
# Ensure Nginx is running

#systemctl status nginx

# if enginx is not running, start it

#systemctl start nginx

# Check if Nginx is listening on port 80
#if ! netstat -tuln | grep ':80'; then
#	echo "Nginx is not listening on port 80. Fixing...."
#	cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Modify nginx to listen on port 80
#sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/nginx.conf

# review if nginx is now listening on port 80
#systemctl restart nginx

#Verify if nginx is now listening
#	if netstat -tuln | grep ':80'; then
#		echo "Nginx is now listening on port 80"
#	else
#		echo "failed to configure nginx to listen"
#	fi
#else
#	echo "nginx is already listening"
#fi

#systemctl enable nginx

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
