#!/usr/bin/env bash
#this script displays list of current running processes

process=$(ps -efH --forest)

echo "USER	PID %CPU %MEM	VSZ 	RSS TTY	STAT START	TIME COMMAND"

while IFS= read -r line; do
	echo "$line"
done <<< "$process" 
