#!/usr/bin/env bash
# This script configues an Ubuntu server 

cp /ect/hosts ~/hosts.new
echo "127.0.0.2			localhost" > ~/hosts.new
echo "8.8.8.8			facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
